name: 'Team Label Action'
description: "Add a team label based on the author's teams in the organization"
author: 'EquityBee'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  repo-token:
    required: true
    description: 'The GITHUB_TOKEN secret'
  organization-name:
    required: true
    description: 'Tis the name/slug of your Github organization (it comes right after https://github.com/)'
  parent-team:
    required: true
    description: 'Tis the name/slug of your Github parent team'
  ignore-labels:
    required: false
    description: 'Optional comma-separated list of labels to ignore'
runs:
  using: 'node12'
  main: 'dist/index.js'
